<template>
  <div class="topdiv">
    <div>
      <form @submit.prevent="searchMovie">
        <input type="text" v-model.trim="addmovietitle" />
        <div class="search jello-horizontal" style="display:flex; flex-direction: column;">
        <button class="search jello-horizontal" @click="searchMovie">
          &#128064;
        </button>
        </div>
      </form>
    </div>
    <div class="cards_list">
      <MovieFormItem
        v-for="(result, index) in results"
        :key="index"
        :result="result"
      />
    </div>
    <br />
    <button @click="AddToMovies">Add</button>
  </div>
</template>

<script>
import axios from "axios";
import MovieFormItem from "@/components/MovieFormItem";

export default {
  name: "MovieForm",
  components: {
    MovieFormItem,
  },
  data() {
    return {
      addmovietitle: null,
      results: null,
    };
  },
  methods: {
    searchMovie() {
      if (this.addmovietitle) {
        const API_KEY = process.env.VUE_APP_API_KEY;
        const SEARCH_URL = "https://api.themoviedb.org/3/search/movie";

        axios({
          method: "get",
          url: SEARCH_URL,
          params: {
            api_key: API_KEY,
            query: this.addmovietitle,
            language: "ko",
          },
        })
          .then((responese) => {
            console.log(responese);
            this.results = responese.data.results;
          })
          .catch((error) => {
            console.log(error);
          });
      }
    },
    AddToMovies() {
      console.log(2);
      this.$store.dispatch("AddToMovies", this.$route.params.id);
    },
  },
};
</script>

<style scoped>
/* ----------------------------------------------
 * Generated by Animista on 2022-11-18 20:42:30
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation jello-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
    transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
    transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
    transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
    transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
    transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
}
@keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
    transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
    transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
    transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
    transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
    transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
}

.jello-horizontal:hover {
  -webkit-animation: jello-horizontal 0.9s both;
  animation: jello-horizontal 0.9s both;
}

.topdiv {
  margin-left: 0;
  margin-right: 0;
}

.cards_list {
  z-index: 0;
  width: 100%;
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}

input {
  width: 250px;
  height: 40px;
  border-top: none;
  border-left: none;
  border-right: none;
  border-bottom: 2px solid rgb(7, 3, 31);
}

.search {
  border: 0;
  outline: 0;
  background-color: transparent;
  font-size: 50px;
}
</style>